apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "hackmd.database" . }}"
  labels:
{{ include "hackmd.labels" . | indent 4 }}
type: Opaque
data:
  DB_NAME: {{ include "hackmd.database.encryptedDatabaseName" . }}
  DB_USER: {{ include "hackmd.database.encryptedUsername" . }}
  DB_PASS: {{ include "hackmd.database.encryptedPassword" . }}
  CMD_DB_URL: {{ include "hackmd.database.encryptedURL" . }}