apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab.core" . }}
  labels:
{{ include "gitlab.labels" . | indent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.expose.type "ingress" }}
  {{ $ingress := .Values.expose.ingress -}}
  GITLAB_HOST: {{ $ingress.host | quote }}
  GITLAB_SSH_PORT: {{ $ingress.sshPort | quote }}
  {{- if .Values.expose.tls.enabled }}
  GITLAB_HTTPS: "true"
  SSL_SELF_SIGNED: "true"
  {{- end }}
  {{- end }}
  {{- if eq .Values.expose.type "nodePort" }}
  {{ $nodePort := .Values.expose.nodePort -}}
  GITLAB_PORT: {{ $nodePort.ports.http.nodePort | quote }}
  GITLAB_SSH_PORT: {{ $nodePort.ports.ssh.nodePort | quote }}
  {{- end }}
  REDIS_HOST: {{ include "gitlab.redis.host" . | quote }}
  REDIS_PORT: {{ include "gitlab.redis.port" . | quote }}
  {{- if (include "gitlab.redis.rawPassword" .) }}
  REDIS_PASSWORD: {{ include "gitlab.redis.encryptedPassword" . }}
  {{- end }}
  DB_HOST: {{ include "gitlab.database.host" . | quote }}
  DB_PORT: {{ include "gitlab.database.port" . | quote }}
  DB_NAME: {{ include "gitlab.database.encryptedDatabaseName" . }}
  DB_USER: {{ include "gitlab.database.encryptedUsername" . }}
  DB_PASS: {{ include "gitlab.database.encryptedPassword" . }}
  RACK_ATTACK_ENABLED: "false"
  GITLAB_GRAVATAR_HTTP_URL: "http://cdn.libravatar.org/avatar/%{hash}?s=%{size}&d=identicon"
  GITLAB_GRAVATAR_HTTPS_URL: "https://seccdn.libravatar.org/avatar/%{hash}?s=%{size}&d=identicon"
  {{- range $name, $value := .Values.core.env }}
  {{- if ne (len ($value | quote)) 0 }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  DB_ADAPTER: postgresql
  GITLAB_DATA_DIR: "/home/git/data"
  GITLAB_BACKUP_SCHEDULE: disable