{{- if .Values.redis.internal.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gitlab.redis" . }}"
  labels:
{{ include "gitlab.labels" . | indent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ include "gitlab.redis.encryptedPassword" . }}
{{- end -}}