{{- $core := .Values.persistence.persistentVolumeClaim.core -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "hackmd.core" . }}"
  labels:
{{ include "hackmd.labels" . | indent 4 }}
    component: hackmd
spec:
  replicas: {{ .Values.core.replicas }}
  serviceName: {{ include "hackmd.core.serviceName" . }}
  selector:
    matchLabels:
{{ include "hackmd.matchLabels" . | indent 6 }}
      component: hackmd
  template:
    metadata:
      labels:
{{ include "hackmd.labels" . | indent 8 }}
        component: hackmd
      annotations:
{{- if .Values.core.podAnnotations }}
{{ toYaml .Values.core.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: hackmd
        image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: CMD_DB_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "hackmd.database" . }}
              key: CMD_DB_URL
      {{- range $name, $value := .Values.core.env }}
      {{- if ne (len ($value | quote)) 0 }}
        - name: {{ $name | quote }}
          value: {{ $value | quote }}
      {{- end }}
      {{- end }}
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 3000
          initialDelaySeconds: 600
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.core.resources | indent 10 }}
        ports:
        - name: http
          containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /home/hackmd/app/public/uploads
          subPath: {{ $core.subPath }}
      {{- if not .Values.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
      {{- else if $core.existingClaim }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ $core.existingClaim }}
      {{- end -}}
      {{- if and .Values.persistence.enabled (not $core.existingClaim) }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "hackmd.core" . }}
      {{- end -}}
    {{- with .Values.core.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
      {{- if eq .Values.core.affinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
{{ include "hackmd.matchLabels" . | indent 18 }}
                  component: hackmd
      {{- else if eq .Values.core.affinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
{{ include "hackmd.matchLabels" . | indent 18 }}
                  component: hackmd
      {{- end }}
    {{- with .Values.core.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}