version: 2
jobs:
  build:
    docker:
    - image: dtzar/helm-kubectl:2.14.3
    steps:
      - checkout
      - run : |
          helm init --skip-refresh -c
          git config --global user.email "zhongziling@vip.qq.com"
          git config --global user.name "$CIRCLE_PROJECT_USERNAME"
          git clone -b gh-pages https://github.com/TimeBye/charts.git /charts
      - run : |
          for chart in $(ls -d */)
          do
            cd $chart
            helm dependency update
            cd ..
            helm package $chart
          done
      - run : |
          mv *.tgz /charts
          mv .circleci/config.yml /charts/.circleci/config.yml
          helm repo index /charts --url https://timebye.github.io/charts/
      - run : |
          cd /charts
          git add .
          git commit -m $CIRCLE_SHA1
          git push https://timebye:${GIT_PASSWORD}@github.com/TimeBye/charts.git

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            only: master