{{- if eq .Values.database.type "internal" -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gitlab.database" . }}"
  labels:
{{ include "gitlab.labels" . | indent 4 }}
type: Opaque
stringData:
  DB_EXTENSION: pg_trgm,btree_gist
  DB_NAME: {{ include "gitlab.database.encryptedDatabaseName" . }}
  DB_USER: {{ include "gitlab.database.encryptedUsername" . }}
  DB_PASS: {{ include "gitlab.database.encryptedPassword" . }}
{{- end -}}