{{- if eq .Values.expose.type "ingress" -}}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ include "hackmd.ingress" . }}"
  labels:
{{ include "hackmd.labels" . | indent 4 }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  {{- if $tls.enabled }}
  tls:
  - hosts:
    - {{ $ingress.host }}
    {{- if $tls.secretName }}
    secretName: {{ $tls.secretName }}
    {{- else }}
    secretName: "{{ include "hackmd.ingress" . }}"
    {{- end }}
  {{- end }}
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "hackmd.core.serviceName" . }}
          servicePort: http
{{- end }}