{{- if and (eq .Values.expose.type "ingress") (eq (include "hackmd.autoGenCert" .) "true") -}}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
{{- $ca := genCA "hackmd-ca" ($tls.certExpiry|int) -}}
{{- $cert := genSignedCert ($ingress.host|quote) nil (list $ingress.host) ($tls.certExpiry|int) $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "hackmd.ingress" . }}"
  labels:
{{ include "hackmd.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}