apiVersion: v1
kind: Service
metadata:
  name: {{ include "hackmd.core.serviceName" . }}
  labels:
{{ include "hackmd.labels" . | indent 4 }}
{{- if or (eq .Values.expose.type "clusterIP") (eq .Values.expose.type "ingress") }}
{{- $clusterIP := .Values.expose.clusterIP }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $clusterIP.port }}
      targetPort: 3000
{{- else if eq .Values.expose.type "nodePort" }}
{{- $nodePort := .Values.expose.nodePort }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ $nodePort.port }}
      targetPort: 3000
      {{- if $nodePort.nodePort }}
      nodePort: {{ $nodePort.nodePort }}
      {{- end }}
{{- else if eq .Values.expose.type "loadBalancer" }}
{{- $loadBalancer := .Values.expose.loadBalancer }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ $loadBalancer.port }}
      targetPort: 3000
{{- end }}
  selector:
{{ include "hackmd.matchLabels" . | indent 6 }}
      component: hackmd
