{{- if and (eq .Values.expose.type "ingress") (eq (include "gitlab.autoGenCert" .) "true") -}}
{{- $ingress := .Values.expose.ingress -}}
{{- $tls := .Values.expose.tls -}}
{{- $ca := genCA "gitlab-ca" ($tls.certExpiry | int) -}}
{{- $cert := genSignedCert $ingress.hosts nil (list $ingress.hosts) ($tls.certExpiry | int) $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gitlab.ingress" . }}"
  labels:
{{ include "gitlab.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}